name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request_target: ~

jobs:
  # Calls a reusable CI workflow to build & test the current repository.
  ci:
    name: ci
    uses: ./.github/workflows/reusable-ci.yml
    with:
      eckit_sha: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit
