name: reusable-ci

on:
  workflow_call:
    eckit_sha:
      required: true
      type: string

jobs:
  ci:
    name: eckit-ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v2
    with:
      repository: ecmwf/eckit
      ref: ${{ inputs.eckit_sha }}
      name_prefix: eckit-
      build_package_inputs: |
        repository: ecmwf/eckit
        sha: ${{ inputs.eckit_sha }}
        self_coverage: true
        dependencies: ecmwf/ecbuild
        dependency_branch: develop
        parallelism_factor: 8
    secrets: inherit
