name: reusable-ci-hpc

on:
  workflow_call:
    inputs:
      eckit:
        required: false
        type: string

jobs:
  ci-hpc:
    name: ci-hpc
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-hpc.yml@main
    with:
      name-prefix: eckit-
      build-inputs: |
        --package: ${{ inputs.eckit || 'ecmwf/eckit@develop' }}
        --modules: |
          ecbuild
          ninja
        --parallel: 64
    secrets: inherit