name: reusable-ci

on:
  workflow_call:
    inputs:
      eckit:
        required: true
        type: string

jobs:
  ci:
    name: eckit-ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v2
    with:
      repository: ${{ inputs.eckit }}
      name_prefix: eckit-
      build_package_inputs: |
        repository: ${{ inputs.eckit }}
        self_coverage: true
        dependencies: ecmwf/ecbuild
        dependency_branch: develop
        parallelism_factor: 8
    secrets: inherit
